---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: 19bucket-1
      aws_access_key: AKIA36PG34ATC2GKMDMS
      aws_secret_key: 2zngrYtw0KF+KHzzdl9ekPGzLMMzX1Btducb6i+z
      state: present
      region: ap-south-1
      versioning: no
      tags:
       -  name: 19bucket-1
          type: example
  - amazon.aws.s3_bucket:
      name: mys3bucket
      state: present
      public_access:
          block_public_acls: false
          ignore_public_acls: false
      policy: "{{ lookup( 'file','mybucket_policy.json' )}}"
      
