---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: lslrth
      aws_access_key: AKIA36PG34ATC2GKMDMS
      aws_secret_key: 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
      policy: "{{ lookup( 'file','mybucket_policy.json' )}}"
      state: present
      region: ap-south-1
      versioning: no
